import { useEffect,useState } from "react";
import { api } from "../lib/api";
type Settings={mode:"local_only"|"local_then_cloud"|"cloud_preferred";cloudConsent:boolean;groqModel:string;hasGroqKey:boolean;ollamaModel:string;ollamaBaseUrl:string};
export function AiSettings(){
 const [settings,setSettings]=useState<Settings|null>(null),[key,setKey]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[details,setDetails]=useState<any>(null);
 useEffect(()=>{void api<Settings>("/ai/settings").then(setSettings).catch(e=>setMessage(e.message));},[]);
 async function save(){if(!settings)return;setBusy(true);try{setSettings(await api<Settings>("/ai/settings",{method:"PUT",body:JSON.stringify({...settings,...(key?{groqApiKey:key}:{})})}));setKey("");setMessage("AI settings saved. Changes apply to new requests.");}catch(e){setMessage(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
 async function probe(provider:string){setBusy(true);setMessage("Testing with a synthetic prompt, not your CV...");try{const value=await api<any>("/ai/providers/test",{method:"POST",body:JSON.stringify({provider}),signal:AbortSignal.timeout(65000)});setDetails(value);setMessage(value.message||"Provider checked.");}catch(e){setMessage(e instanceof Error?e.message:"Test failed");}finally{setBusy(false);}}
 return <section className="panel" id="ai-settings"><h2>AI provider and privacy</h2><p>CV import, editing and quick discovery work without AI. Cloud AI is optional and uses your own API key; provider quotas and charges may apply.</p>{message&&<p role="status">{message}</p>}{settings&&<><div className="form-grid"><label>AI mode<select value={settings.mode} onChange={e=>setSettings({...settings,mode:e.target.value as Settings["mode"]})}><option value="local_only">Local only (default)</option><option value="local_then_cloud">Local, then cloud fallback</option><option value="cloud_preferred">Cloud preferred, then local</option></select></label><label>Groq structured model<select value={settings.groqModel} onChange={e=>setSettings({...settings,groqModel:e.target.value})}><option>openai/gpt-oss-20b</option><option>openai/gpt-oss-120b</option></select></label><label className="full">Your Groq API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder={settings.hasGroqKey?"A key is configured. Leave blank to keep it.":"Stored only in this installation's local secrets folder"}/></label></div><label className="choice-row"><input type="checkbox" checked={settings.cloudConsent} onChange={e=>setSettings({...settings,cloudConsent:e.target.checked})}/><span>I allow CV, profile, job and application content used by AI features to be sent to my selected cloud provider (or a configured non-local Ollama server).<small>Local-only with loopback Ollama sends none of this to Groq. Uncheck to revoke permission. Normal backups exclude the key; private filesystem backups may include it.</small></span></label><p>Local model: {settings.ollamaModel} at {settings.ollamaBaseUrl}</p><div className="actions"><button disabled={busy} onClick={save}>Save AI settings</button><button disabled={busy} onClick={()=>probe("ollama")}>Test local AI</button><button disabled={busy||!settings.cloudConsent} onClick={()=>probe("groq")}>Test cloud AI</button><button disabled={busy||!settings.hasGroqKey} onClick={()=>{void api<Settings>("/ai/settings",{method:"PUT",body:JSON.stringify({...settings,mode:"local_only",cloudConsent:false,clearKey:true})}).then(s=>{setSettings(s);setMessage("Saved key removed; local-only mode selected.");}).catch(e=>setMessage(e.message));}}>Remove saved key</button></div></>}{details&&<p>Provider: {details.provider}; model: {details.model}; {details.available?"available":"needs attention"}{details.latencyMs!==undefined?`; test took ${(details.latencyMs/1000).toFixed(1)} seconds`:""}{details.code?`; ${details.code}`:""}</p>}</section>;
}
