import {useEffect,useState} from "react";
import {api} from "../lib/api";
import {navigate} from "../lib/navigation";
export type Task={id:string;kind:string;subjectKey:string;status:string;phase:string;counters:Record<string,number>;result:any;message:string;error:{code:string;message:string}|null;createdAt:string;startedAt:string|null;updatedAt:string;completedAt:string|null};
export const taskActive=(task:Task)=>["QUEUED","RUNNING","CANCELLING"].includes(task.status);
export function TaskProgress({task,onChange}:{task:Task;onChange?:()=>void}){
 const c=task.counters;const done=c.sectionsDone??c.jobsAnalyzed??c.sourcesScanned??0,total=c.sectionsTotal??c.jobsToAnalyze??c.sourcesTotal;
 const active=taskActive(task);const [error,setError]=useState("");
 async function action(name:string){try{await api(`/tasks/${task.id}/${name}`,{method:"POST",body:"{}"});onChange?.();}catch(e){setError(e instanceof Error?e.message:"Task action failed");}}
 return <section className="task-progress" aria-label={`${task.kind.replaceAll("_"," ")} progress`}><div className="panel-title"><strong>{task.kind.replaceAll("_"," ")}</strong><span>{task.status.replaceAll("_"," ")}</span></div><p role="status">{task.message}</p>{active&&(total!==undefined&&total>0?<><progress value={done} max={total} aria-label={task.phase}/><small>{task.phase.replaceAll("_"," ")}: {done} / {total} (this phase)</small></>:<progress aria-label="Working; total not known yet"/>)}<div className="task-counts">{Object.entries(c).map(([k,v])=><span key={k}>{k.replace(/([A-Z])/g," $1")}: <strong>{v}</strong></span>)}</div>{task.error&&<p className="task-error">{task.error.code}: {task.error.message}</p>}{error&&<p role="alert">{error}</p>}{active?<><p className="muted">You can leave this page. Keep ApplyLite running and the computer awake.</p><button disabled={task.status==="CANCELLING"} onClick={()=>action("cancel")}>Cancel task</button></>:null}{["FAILED","INTERRUPTED","CANCELLED"].includes(task.status)&&task.kind!=="cv_enhance"&&<button onClick={()=>action("retry")}>Retry task</button>}</section>;
}
export function ActivityCentre(){const[tasks,setTasks]=useState<Task[]>([]);useEffect(()=>{let alive=true;const load=()=>void api<Task[]>("/tasks").then(t=>{if(alive)setTasks(t);}).catch(()=>{});load();const timer=setInterval(load,2000);return()=>{alive=false;clearInterval(timer);};},[]);const active=tasks.filter(taskActive);return <details className="activity-centre"><summary>Activity {active.length?`(${active.length} running/queued)`:""}</summary>{tasks.slice(0,5).map(t=><button key={t.id} onClick={()=>navigate(t.kind==="cv_enhance"?"/cv":"/discover")}><strong>{t.kind.replaceAll("_"," ")}</strong><small>{t.status.toLowerCase()}</small></button>)}{!tasks.length&&<p>No background tasks yet.</p>}</details>;}
